name: WPS Auto Click
on:
  schedule:
    - cron: '00 10 * * *'
    - cron: '00 00 * * *'
  workflow_dispatch:

jobs:
  run_task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Cache PW Browser
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-pw-${{ hashFiles('node_modules/playwright/package.json','package.json') }}

      - name: Install npm
        run: npm ci

      - name: Install playwright chromium
        run: npx playwright install chromium --with-deps

      - name: Run script
        env:
          WPS_COOKIES: ${{ secrets.WPS_COOKIES }}
        run: node auto-click.js

      # ==========新增：上传截图文件为工件==========
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: wps-screenshot
          path: |
            *.png
